services:
  mininet:
    image: scc-registry.lancs.ac.uk/teaching/scc_333/mn-stratum:25
    hostname: mininet
    container_name: mininet
    privileged: true
    tty: true
    stdin_open: true
    restart: always
    environment:
      - DISPLAY=${DISPLAY} # Uncomment if X11 forwarding is needed
    volumes:
      - ./tmp:/tmp
      - ./mininet:/mininet
      - ./p4src:/p4src
      - ./util:/util
    ports:
      - "50001:50001"
      - "50002:50002"
      - "50003:50003"
      - "50004:50004"
      - "60001:60001"
    # NGSDN_TOPO_PY is a Python-based Mininet script defining the topology. Its
    # value is passed to docker-compose as an environment variable, defined in
    # the Makefile.
    command: python3 /mininet/topo.py
    entrypoint: /bin/bash -c
